name: Push
on:
  push:
    tags:
      - 'kdot-auth-proxy@*'
  workflow_dispatch:
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: startsWith(github.ref, 'refs/tags/kdot-auth-proxy@')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set tag
        env:
          APP: kdot-auth-proxy
        run: |
          node scripts/setTag.cjs
          echo "APP_TAG=$APP_TAG" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: generates/kdot-auth-proxy:${{ env.APP_TAG }}
          file: ./apps/kdot-auth-proxy/Dockerfile

