name: Push
on:
  push:
    tags:
      - 'kdot-auth-proxy@*'
  workflow_dispatch:
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: startsWith(github.ref, 'refs/tags/kdot-auth-proxy@')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install zx
        run: npm i -g zx
      - name: Set tag
        env:
          APP: kdot-auth-proxy
        run: ./scripts/setTag.js
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: generates/kdot-auth-proxy:${{ env.APP_TAG }},generates/kdot-auth-proxy:latest
          file: ./apps/kdot-auth-proxy/Dockerfile

